name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install . pytest mypy ruff
      - name: Lint
        run: ruff aios_io/*.py tests
      - name: Type check
        run: mypy aios_io/*.py
      - name: Test
        run: pytest
